name: Testar

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  gerar:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v7

      - name: Configurar Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 24
          cache: npm

      - name: Instalar dependências
        run: npm ci

      - name: Gerar build
        run: npm run build

      - name: Anexar build
        uses: actions/upload-artifact@v7
        with:
          name: build
          path: alvo

  testar:
    needs: gerar
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.63.0-noble

    steps:
      - name: Baixar código
        uses: actions/checkout@v7

      - name: Instalar dependências
        run: npm ci

      - name: Baixar build
        uses: actions/download-artifact@v8
        with:
          name: build
          path: alvo

      - name: Executar testes
        run: npm test

      - name: Anexar resultados dos testes
        if: ${{ failure() }}
        uses: actions/upload-artifact@v7
        with:
          name: test-results
          path: test-results/

  publicar:
    if: ${{ needs.testar.result == 'success' && github.event_name == 'push' }}
    needs: [gerar, testar]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Baixar build
        uses: actions/download-artifact@v8
        with:
          name: build
          path: alvo

      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v5

      - name: Empacotar site
        uses: actions/upload-pages-artifact@v3
        with:
          path: alvo

      - name: Publicar no GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
